[package]

name = "rotuli"
version = "0.0.1"
authors = ["Konsta Hölttä <sooda@iki.fi>"]

[dependencies]
glob = "*"
serde_yaml = "*"
tera = "1.3"
# same as tera
serde = { version = "1.0", features = ["derive"] }
regex = "*"
